export type SubclassName =
  | "Beastbound"
  | "Call of the Brave"
  | "Call of the Slayer"
  | "Divine Wielder"
  | "Elemental Origin"
  | "Nightwalker"
  | "Primal Origin"
  | "School of Knowledge"
  | "School of War"
  | "Stalwart"
  | "Syndicate"
  | "Troubadour"
  | "Vengeance"
  | "Warden of Renewal"
  | "Warden of the Elements"
  | "Wayfinder"
  | "Winged Sentinel"
  | "Wordsmith"
  | "";